const puertoPrincesaBarangays = <String>[
  'Babuyan',
  'Bacungan',
  'Bagong Bayan',
  'Bagong Pag-Asa',
  'Bagong Sikat',
  'Bagong Silang',
  'Bahile',
  'Bancao-bancao',
  'Binduyan',
  'Buenavista',
  'Cabayugan',
  'Concepcion',
  'Inagawan',
  'Irawan',
  'Iwahig',
  'Kalipay',
  'Kamuning',
  'Langogan',
  'Liwanag',
  'Lucbuan',
  'Mabuhay',
  'Macarascas',
  'Magkakaibigan',
  'Maligaya',
  'Manalo',
  'Manggahan',
  'Maningning',
  'Maoyon',
  'Marufinas',
  'Maruyogon',
  'Masigla',
  'Masikap',
  'Masipag',
  'Matahimik',
  'Matiyaga',
  'Maunlad',
  'Milagrosa',
  'Model',
  'Montible',
  'Napsan',
  'New Panggangan',
  'Pagkakaisa',
  'Princesa',
  'Salvacion',
  'San Jose',
  'San Miguel',
  'San Pedro',
  'San Rafael',
  'Santa Cruz',
  'Santa Lourdes',
  'Santa Lucia',
  'Santa Monica',
  'Seaside',
  'Sicsican',
  'Simpocan',
  'Tagabinit',
  'Tagburos',
  'Tagumpay',
  'Tanabag',
  'Tanglaw',
  'Mangingisda',
  'Inagawan Sub-Colony',
  'Luzviminda',
  'Mandaragat',
  'San Manuel',
  'Tiniguiban',
];
