import '../models/app_models.dart';

const demoAdminEmail = 'admin@andrewssupermarket.com';
const demoAdminPassword = 'password';
final _samplePriceUpdatedAt = DateTime(2026, 7, 31);
const sampleBestSellerProductIds = <String>['1', '2', '3', '4', '6', '9'];

final sampleCategories = <Category>[
  Category(
    id: '1',
    name: 'Beverages',
    normalizedName: 'beverages',
    isActive: true,
    isArchived: false,
    sortOrder: 1,
  ),
  Category(
    id: '2',
    name: 'Snacks',
    normalizedName: 'snacks',
    isActive: true,
    isArchived: false,
    sortOrder: 2,
  ),
  Category(
    id: '3',
    name: 'Canned Goods',
    normalizedName: 'canned goods',
    isActive: true,
    isArchived: false,
    sortOrder: 3,
  ),
  Category(
    id: '4',
    name: 'Noodles',
    normalizedName: 'noodles',
    isActive: true,
    isArchived: false,
    sortOrder: 4,
  ),
  Category(
    id: '5',
    name: 'Condiments',
    normalizedName: 'condiments',
    isActive: true,
    isArchived: false,
    sortOrder: 5,
  ),
  Category(
    id: '6',
    name: 'Personal Care',
    normalizedName: 'personal care',
    isActive: true,
    isArchived: false,
    sortOrder: 6,
  ),
  Category(
    id: '7',
    name: 'Household',
    normalizedName: 'household',
    isActive: true,
    isArchived: false,
    sortOrder: 7,
  ),
  Category(
    id: '8',
    name: 'Others',
    normalizedName: 'others',
    isActive: true,
    isArchived: false,
    sortOrder: 8,
  ),
];

final sampleProducts = <Product>[
  Product(
    id: '1',
    name: 'Purified Water',
    categoryId: '1',
    categoryNameSnapshot: 'Beverages',
    quantity: '500',
    unit: 'mL',
    type: 'bottle',
    referencePriceCentavos: 1200,
    priceUpdatedAt: _samplePriceUpdatedAt,
    isActive: true,
    isArchived: false,
    validOrderedQuantity: 0,
    validOrderCount: 0,
  ),
  Product(
    id: '2',
    name: 'Corn Chips',
    categoryId: '2',
    categoryNameSnapshot: 'Snacks',
    quantity: '100',
    unit: 'g',
    type: 'pack',
    referencePriceCentavos: 1400,
    priceUpdatedAt: _samplePriceUpdatedAt,
    isActive: true,
    isArchived: false,
    validOrderedQuantity: 0,
    validOrderCount: 0,
  ),
  Product(
    id: '3',
    name: 'Instant Coffee',
    categoryId: '8',
    categoryNameSnapshot: 'Others',
    quantity: '50',
    unit: 'g',
    type: 'pack',
    referencePriceCentavos: 2800,
    priceUpdatedAt: _samplePriceUpdatedAt,
    isActive: true,
    isArchived: false,
    validOrderedQuantity: 0,
    validOrderCount: 0,
  ),
  Product(
    id: '4',
    name: 'Evaporated Milk',
    categoryId: '3',
    categoryNameSnapshot: 'Canned Goods',
    quantity: '330',
    unit: 'g',
    type: 'can',
    referencePriceCentavos: 3600,
    priceUpdatedAt: _samplePriceUpdatedAt,
    isActive: true,
    isArchived: false,
    validOrderedQuantity: 0,
    validOrderCount: 0,
  ),
  Product(
    id: '5',
    name: 'Powdered Milk',
    categoryId: '8',
    categoryNameSnapshot: 'Others',
    quantity: '1',
    unit: 'kg',
    type: 'pack',
    referencePriceCentavos: 21500,
    priceUpdatedAt: _samplePriceUpdatedAt,
    isActive: true,
    isArchived: false,
    validOrderedQuantity: 0,
    validOrderCount: 0,
  ),
  Product(
    id: '6',
    name: 'Pancit Canton',
    categoryId: '4',
    categoryNameSnapshot: 'Noodles',
    quantity: '80',
    unit: 'g',
    type: 'pack',
    referencePriceCentavos: 1850,
    priceUpdatedAt: _samplePriceUpdatedAt,
    isActive: true,
    isArchived: false,
    validOrderedQuantity: 0,
    validOrderCount: 0,
  ),
  Product(
    id: '7',
    name: 'Toothpaste',
    categoryId: '6',
    categoryNameSnapshot: 'Personal Care',
    quantity: '150',
    unit: 'g',
    type: 'tube',
    referencePriceCentavos: 9900,
    priceUpdatedAt: _samplePriceUpdatedAt,
    isActive: true,
    isArchived: false,
    validOrderedQuantity: 0,
    validOrderCount: 0,
  ),
  Product(
    id: '8',
    name: 'Laundry Powder',
    categoryId: '7',
    categoryNameSnapshot: 'Household',
    quantity: '1',
    unit: 'kg',
    type: 'bag',
    referencePriceCentavos: 9200,
    priceUpdatedAt: _samplePriceUpdatedAt,
    isActive: true,
    isArchived: false,
    validOrderedQuantity: 0,
    validOrderCount: 0,
  ),
  Product(
    id: '9',
    name:
        'Mega Crunchy Extra Special Sweet Spicy Garlic Barbecue Family Fiesta Corn Snack Supreme',
    categoryId: '2',
    categoryNameSnapshot: 'Snacks',
    quantity: '180',
    unit: 'g',
    type: 'pack',
    referencePriceCentavos: 2750,
    priceUpdatedAt: _samplePriceUpdatedAt,
    isActive: true,
    isArchived: false,
    validOrderedQuantity: 0,
    validOrderCount: 0,
  ),
];

const defaultPublicNotice =
    'Product availability and final prices will be confirmed by Andrew\'s Supermarket.';
